### ISSUE TITLE
coroutine

### ISSUE THREAD

**Issue by 10kkm** [andrersp/aioanticaptcha#1]
getting coroutine instead of g_response

**Comment by andrersp** [comment]
in which method?

**Comment by 10kkm** [comment]
HCaptchaProxyless

**Comment by andrersp** [comment]
Solved on PR https://github.com/andrersp/aioanticaptcha/tree/1-coroutine

**Comment by 10kkm** [comment]
did u release it?

**Comment by andrersp** [comment]
yeah.

https://pypi.org/project/python3-aioanticaptcha/
